version: '3.8'

services:
  postgres:
    container_name: postgres
    image: postgres:13
    volumes:
      - postgres_volume:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB_NAME: postgres
    ports:
      - 5432:5432

  pgadmin:
    image: dpage/pgadmin4
    container_name: adonis_pgadmin #you can change this
    depends_on:
      - postgres
    ports:
      - "5052:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: pgadmin@pgadmin.org
      PGADMIN_DEFAULT_PASSWORD: root
    restart: always

  adonis_app:
    container_name: adonis_app
    depends_on:
      - postgres
    build:
      context: .
    ports:
      - 3333:3333
    volumes:
      - .:/home/node/app

volumes:
  postgres_volume:
